
export default {
    ADD_NEW_CAR_ACTION: 'ADD_NEW_CAR_ACTION', 
    GET_ALL_CAR_ACTION: 'GET_ALL_CAR_ACTION', 
    DELETE_CAR_ACTION: 'DELETE_CAR_ACTION', 
    PURCHASE_CAR_ACTION: 'PURCHASE_CAR_ACTION', 
    GET_CAR_BY_SELLING_DATE_ACTION: ' GET_CAR_BY_SELLING_DATE_ACTION',
    GET_REPORT_ACTION: 'GET_REPORT_ACTION',
    GET_CARS_WITH_OPTIMISTIC_LOCK: 'GET_CARS_WITH_OPTIMISTIC_LOCK',
    EDIT_CAR_ACTION:'EDIT_CAR_ACTION'

}