

export default {
    ADD_NEW_CAR_MUTATION : 'ADD_NEW_CAR_MUTATION' , 
    GET_ALL_CARS_MUTATION : 'GET_ALL_CARS_MUTATION' , 
    DELETE_CAR_MUTATION: 'DELETE_CAR_MUTATION' , 
    PURCHASE_CAR_MUTATION: ' PURCHASE_CAR_MUTATION',
    GET_CAR_BY_SELLING_DATE_MUTATION: 'GET_CAR_BY_SELLING_DATE_MUTATION',
    GET_REPORT_MUTATION: 'GET_REPORT_MUTATION',
    CREATE_CAR_WITH_OPTEMISTIC_LOCK: `CREATE_CAR_WITH_OPTEMISTIC_LOCK`
}